### ISSUE TITLE
HTML Serializer object syntax

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-helpers#26]
I think that most of the use cases for HTML Serializers are for labels (that's a guess). The label property is nested under `element.data.label`, so if a user has multiple labels, they will still need to use a `switch` inside their object syntax. In that case, is the object syntax simply overcomplicating things? (Genuine question.)

```js
const htmlSerializer = {
  label: ({ children, element }) => {
    switch (element.data?.label) {
    }
     case 'codespan':
      return `<code>${children.join('')}<code/>`
    case 'highlight':
     return `<mark>${children.join('')}</mark>`
    case 'banner':
      return `<div class="banner">${children.join('')}</div>`
    }
  }
}
```
As opposed to:
```js
const htmlSerializer = (type, element, content, children) => {
  switch (element.data?.label) {
    case 'codespan':
      return `<code>${children.join('')}<code/>`
    case 'highlight':
      return `<mark>${children.join('')}</mark>`
    case 'banner':
      return `<div class="banner">${children.join('')}</div>`
  }
}
```
_Pardon my janky, untested code snippets._

**Comment by angeloashmore** [comment]
I think a big use case for the serializer is to add class names or change element types from the defaults. For example, if you need to change heading levels for a section of content, you can do so with the serializer easily:

```js
const htmlSerializer = {
  heading1: ({ children }) => `<h2>${children.join("")}</h2>`,
  heading2: ({ children }) => `<h3>${children.join("")}</h3>`,
  heading3: ({ children }) => `<h4>${children.join("")}</h4>`,
};
```

I believe only the `span` element would make use of labels. In that case, it depends on how the user wants to treat labels. In some cases, it is just for a class name, while in others, it is to change the rendered element like in your example.

So a more accurate comparison would be a function like this:

Object:
```js
const htmlSerializer = {
  span: ({ children, element }) => {
    switch (element.data?.label) {
      case "codespan":
        return `<code>${children.join("")}<code/>`;
      case "highlight":
        return `<mark>${children.join("")}</mark>`;
      default:
        return `<span class="${element.data.label}">${children.join("")}</span>`;
    }
  },
};
```

Function:
```js
const htmlSerializer = (type, element, content, children) => {
  switch (type) {
    case Element.span: {
      switch (element.data?.label) {
        case "codespan":
          return `<code>${children.join("")}<code/>`;
        case "highlight":
          return `<mark>${children.join("")}</mark>`;
        default:
          return `<span class="${element.data.label}">${children.join("")}</span>`;
      }
    }
  }
};
```

Adding another element looks like this:

Object:
```diff
  const htmlSerializer = {
+   heading1: ({ children }) => `<h1>${children.join("")}</h1>`,
    span: ({ children, element }) => {
      switch (element.data?.label) {
        case "codespan":
          return `<code>${children.join("")}<code/>`;
        case "highlight":
          return `<mark>${children.join("")}</mark>`;
        default:
          return `<span class="${element.data.label}">${children.join("")}</span>`;
      }
    },
  };
```

Function:
```diff
  const htmlSerializer = (type, element, content, children) => {
    switch (type) {
+     case Element.heading1: {
+       return `<h1>${children.join("")}</h1>`;
+     }
+
      case Element.span: {
        switch (element.data.label) {
          case "codespan":
            return `<code>${children.join("")}<code/>`;
          case "highlight":
            return `<mark>${children.join("")}</mark>`;
          default:
            return `<span class="${element.data.label}">${children.join("")}</span>`;
        }
      }
    }
  };
```

From this, I think we can see all elements *except* spans benefit from the object syntax due to its brevity. Spans are practically identical between the two types of serializers.

In general, the object syntax promotes better encapsulation as well since we know spans, for example, will only be touched within the `spans` property. In the function serializers, users are open to any practice they want, which could lead to unpredictable logic. Some use cases require a function, and it is up to the developer to decide if the logic should be nested within the element's type (within an object serializer), or if the whole serializer should be treated as a function. Preference should be toward the former.
