### ISSUE TITLE
[bug] `get()` doesn't accept single predicate

### ISSUE THREAD

**Issue by samlfair** [prismicio/prismic-helpers#27]
In v5, `query()` will accept a single predicate or an array of predicates. In v6, `get()` doesn't recognize a single predicate, and returns unfiltered results:

```js
import * as prismic from '@prismicio/client';
import * as prismicH from '@prismicio/helpers';
import fetch from 'node-fetch';

const repoName = 'prismicio-docs-v3'
const endpoint = prismic.getEndpoint(repoName);
const client = prismic.createClient(endpoint, { fetch });

const init = async () => {
  const docs = await client.get(
    prismic.predicate.at('document.type', 'core_concepts_article')
  );
  console.log(docs.results[0]);
};

init();

```

**Comment by samlfair** [comment]
My mistake, I was misreading the results.

**Comment by angeloashmore** [comment]
@samlfair I assume this was for `prismic-javascript` rather than `prismic-helpers`?

It sounds like you figured it out, but `get` takes in an object as its first parameter. You can provide one or more predicates (a single predicate or an array of predicates) using the `predicates` property:

```ts
client.get({
  predicates: prismic.predicate.at('document.type', 'core_concepts_article')
})
```

For backwards compatibility, v6 includes a `client.query` method as an alias for `client.get`. We could make `query` act like v5's `query` by allowing one or more predicates as the first parameter:

```ts
client.query(prismic.predicate.at('document.type', 'core_concepts_article'))
```

Ultimately, I think we would deprecate the `query` method, however.
