### ISSUE TITLE
Create a helper to transform html code in RichText object

### ISSUE THREAD

**Issue by Joaovsa7** [prismicio/prismic-helpers#39]
### Is your feature request related to a problem? Please describe.

Hey Guys, 

I see the function `prismicHelper.asHtml` and i have an idea based on a workaround that i did on my team.

Currently on my team we have a tool to create prismic pages massively. We use a spreadsheet file (csv/excel) to create the fields of the prismic document and upload it to prismic via `import/export` feature.

e.g

|   title	|   banner.title (RichTextField)	|  
|---	|---	|
|   Title of the page	|   ```<h1>Heading</h1> ```

So, we have a `helper function` that transform the given html(argmument) to a `RichText` field of prismic.

### Describe the solution you'd like

I would like to have a `helper` on `@prismic-helpers` package to transform `html code` to `RichText` code. 

### Describe alternatives you've considered

Created my own helper.

**Comment by lihbr** [comment]
Hey there, thank you so much for your contribution, and sorry for the delay it took to get back to you.

`@prismicio/helpers` aims at providing helpers to template Prismic data in applications using Prismic. Therefore, we don't think this package is suited for holding helpers responsible for transforming data that gets imported to Prismic (that is to say, data not handled by the end application itself).

Because of that, we'll close this issue as we don't think it belongs to this package. May it be reopened if further consideration is desired.

---

With all of that in mind, your request remains completely valid and we'll keep track of it. We plan to introduce at a later time (no ETA yet) another package that helps create import artifacts for the import/export feature and such a helper would very likely be part of it.

In the meantime, it'd be awesome if you could share your own helper here so that people in a similar case as you can build on top of it.
