### ISSUE TITLE
Date returned by Prismic API seem to be inconsistant sometimes

### ISSUE THREAD

**Issue by faresd** [prismicio/prismic-helpers#4]
This code indicates that there are some cases where the date returned by the API doesn't have the same format, can you investigate?

https://github.com/prismicio/prismic-helpers/blob/a4ce373e2cab1e8d0c9906998084fbce8d7b2671/src/date.js#L1-L7

**Comment by lihbr** [comment]
Hey Fares (better late than never haha)! Just for the sake of answering you, and for letting everyone know, Prismic actually has two types of time-related fields:
- The Date field;
- The Timestamp field.

The first one returns an ISO 8601 date that looks like that: `2021-05-12`.
The second returns an ISO 8601 date and time that again looks like that: `2021-05-11T22:00:00+0000`.

And now, as you noticed it this check is made to identify timestamp fields. It then proceeds to transform them from their ISO 8601 date and time format to ECMAScript simplified ISO 8601 date and time format that looks like that: `2021-05-11T22:00:00.000+00:00` This is done in order to ensure better browser compatibility ☺️

ECMAScript 2020 language specification: https://262.ecma-international.org/11.0/#sec-date-time-string-format

Cheers!

**Comment by faresd** [comment]
@lihbr well what I don't understand here why do we expect timestamp & simplified date,  Prismic  has 2 different date types (custom types) data & timestamp.
So why here we use the same helper for both!!

**Comment by lihbr** [comment]
Haha, nice question! I guess it's just for convenience so you don't have to think about it being a date or a timestamp coming from the API? I like it this way to be honest ^^'

**Comment by faresd** [comment]
@arnaudlewis (FYI something we have discussed before ) @lihbr In fact here the problem is not the helper but the API, the API should only return one type, especially in GraphQL as it is typed.

**Comment by lihbr** [comment]
Types from the API will be `string` anyway ^^' I don't know about making the date and timestamp field output the same~
